---
# file roles/all_users_groups/tasks/add_galaxy_users.yml
- name: Create galaxy groups on "{{ hostname }}"
  become: true
  group:
          name: "{{ galaxy_user[item.key] }}"
          gid: "{{ galaxy_user_id[item.key] }}"
  loop: "{{ lookup('dict', galaxy_user) }}"
- name: Create galaxy users on "{{ hostname }}"
  become: true
  user:
          name: "{{ galaxy_user[item.key] }}"
          comment: Galaxy user for "{{ item.key }}"
          uid: "{{ galaxy_user_id[item.key] }}"
          group: "{{ galaxy_user[item.key] }}"
          home: "/home/{{ galaxy_user[item.key] }}"
          shell: /bin/bash
  loop: "{{ lookup('dict', galaxy_user) }}"
- name: Allow ubuntu to ssh to server "{{ hostname }}"
  become: true
  lineinfile:
          path: /etc/ssh/sshd_config
          insertafter: EOF
          line: 'AllowUsers ubuntu'
  notify: Restart sshd
